import React from "react";
import { Inter } from "next/font/google";

import "./globals.css";
import StyledComponentsRegistry from "@/lib/AntdRegistry";
import StoreProvider from "@/redux/StoreProvider";
import AntdLayout from "@/components/layout/AntdLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: React.PropsWithChildren) => (
  <html lang="en">
    <StoreProvider>
      <body className={inter.className} suppressHydrationWarning={true}>
        <StyledComponentsRegistry>
          <AntdLayout>{children}</AntdLayout>
        </StyledComponentsRegistry>
      </body>
    </StoreProvider>
  </html>
);

export default RootLayout;
